apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.backend.port }}

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/{{ .Values.postgres.database }}

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.username }}

            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgres.password }}

            - name: SPRING_DATA_REDIS_HOST
              value: redis

            - name: SPRING_DATA_REDIS_PORT
              value: "{{ .Values.redis.port }}"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

            - name: AI_SERVICE_URL
              value: http://ai-service:8000

            - name: JWT_ISSUER_URI
              value: http://localhost:8081/realms/expense-realm

            - name: JWT_JWK_SET_URI
              value: http://keycloak:8080/realms/expense-realm/protocol/openid-connect/certs

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend

  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}