apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: keycloak

  template:
    metadata:
      labels:
        app: keycloak

    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}

          args:
            - start-dev

          ports:
            - containerPort: {{ .Values.keycloak.port }}

          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: {{ .Values.keycloak.adminUsername }}

            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: {{ .Values.keycloak.adminPassword }}

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: keycloak

  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }}