spring.application.name=ai-expense-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/expense_db
spring.datasource.username=expense_user
spring.datasource.password=expense_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=localhost:9092

spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

ai.service.url=${AI_SERVICE_URL:http://127.0.0.1:8000}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=expense-audit-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.ai_expense_backend.event

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:8081/realms/expense-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:8081/realms/expense-realm/protocol/openid-connect/certs}

resilience4j.circuitbreaker.instances.aiService.sliding-window-size=5
resilience4j.circuitbreaker.instances.aiService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.aiService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.aiService.permitted-number-of-calls-in-half-open-state=2

resilience4j.retry.instances.aiService.max-attempts=3
resilience4j.retry.instances.aiService.wait-duration=500ms